--[[
  _                    _                     _____           __        __              __     ______  
 | |    ___   __ _  __| | ___ _ __          |__  /___ _ __ __\ \      / /_ _ _ __ ___  \ \   / /___ \ 
 | |   / _ \ / _` |/ _` |/ _ \ '__|  _____    / // _ \ '__/ _ \ \ /\ / / _` | '__/ _ \  \ \ / /  __) |
 | |__| (_) | (_| | (_| |  __/ |    |_____|  / /|  __/ | | (_) \ V  V / (_| | | |  __/   \ V /  / __/ 
 |_____\___/ \__,_|\__,_|\___|_|            /____\___|_|  \___/ \_/\_/ \__,_|_|  \___|    \_/  |_____|
                                                                                                      
]]--
local gid = game.PlaceId -- Place ID

if gid == 301549746 then
  loadstring(game:HttpGet('https://raw.githubusercontent.com/scytheXlol/ZeroWare-V2/refs/heads/main/lil-w.lua'))() -- Counter Blox
else
  loadstring(game:HttpGet('https://raw.githubusercontent.com/scytheXlol/ZeroWare-V2/refs/heads/main/universal.lua'))() -- Universal
end


-- V2.0.3 - last version.
-- more games soon...
